// AUTO-GENERATED by src/data/gen-api.ts from the backend docs/openapi.json (sha256:c5dfa2e27bc323fd). DO NOT EDIT.
// Regenerate with `pnpm gen:api`; `pnpm gen:api --check` fails on drift.
/* eslint-disable */
export type paths = {
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream (text/event-stream)
         * @description Query `channels` (comma separated: ops, payments, messages, settings, notifications; default all permitted). Resume with the `Last-Event-ID` header (or `lastEventId`). Channels the caller lacks permission for are dropped and listed in `ready.denied`.
         */
        get: {
            parameters: {
                query?: {
                    channels?: string;
                    lastEventId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server time in the business timezone */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            bizDate: string;
                            dateLabel: string;
                            minutes: number;
                            /** Format: date-time */
                            now: string;
                            tz: string;
                            weekday: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** @description RFC 9457 problem details. For guard failures title and detail are the exact strings the dashboard toasts. */
        Problem: {
            /** @description Machine-readable code, e.g. SLOT_UNAVAILABLE, OVER_LIMIT, VERSION_CONFLICT */
            code: string;
            detail: string;
            errors?: {
                message: string;
                path: string;
            }[];
            meta?: {
                [key: string]: unknown;
            };
            requestId?: string;
            status: number;
            title: string;
            /** @description urn:oasis:problem:<code in kebab-case> */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
