import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { Emitter } from './emit'
import { CompileError } from './errors'
import { applyCopy, applyCopyToTree, applyPatches, loadPatchConfig } from './patches'
import { parseTemplate, textOf, walkEls } from './parse'

export const COMPILER_VERSION = '1.0.0'
export const SCREENS = ['operations', 'payments', 'settings'] as const
export type ScreenId = (typeof SCREENS)[number]

export interface CompileOptions {
  root: string
  variant: 'prod' | 'parity'
  tplIds: boolean
  allowComplexExpr: boolean
}

/** relative path -> file bytes. For screen outputs the path is relative to --out, for shared outputs to the repo root. */
export type Outputs = Record<string, string | Buffer>

const sha = (b: string | Buffer): string => crypto.createHash('sha256').update(b).digest('hex')
const read = (root: string, ...p: string[]): string => fs.readFileSync(path.join(root, ...p), 'utf8')

/** The `FULL_PAGE_CSS` constant of the original runtime, read from the extracted runtime so it cannot drift. */
export function fullPageCss(root: string): string {
  const src = read(root, 'design/extracted/runtime/dc-runtime.js')
  const m = src.match(/var FULL_PAGE_CSS = ("(?:[^"\\]|\\.)*");/)
  if (!m) throw new CompileError('could not find FULL_PAGE_CSS in design/extracted/runtime/dc-runtime.js')
  return JSON.parse(m[1]!) as string
}

interface HelmetCss {
  fonts: string
  global: string
}

/** The two helmet <style> blocks as the template carries them; they must equal the extracted helmet.*.css files. */
function helmetCss(
  root: string,
  screen: string,
  nodes: ReturnType<typeof parseTemplate>['nodes'],
): HelmetCss {
  const styles: string[] = []
  let helmets = 0
  walkEls(nodes, (el) => {
    if (el.tag === 'sc-helmet') helmets++
    if (el.tag === 'style') styles.push(textOf(el.children))
  })
  if (helmets !== 1) throw new CompileError(`${screen}: expected exactly one <helmet>, found ${helmets}`)
  const fonts = styles.filter((s) => s.includes('@font-face'))
  const global = styles.filter((s) => !s.includes('@font-face'))
  if (styles.length !== 2 || fonts.length !== 1 || global.length !== 1) {
    throw new CompileError(`${screen}: expected one font-face <style> and one global <style> in the helmet`)
  }
  const fileFonts = read(root, 'design/extracted', screen, 'helmet.fonts.css')
  const fileGlobal = read(root, 'design/extracted', screen, 'helmet.global.css')
  if (fonts[0] !== fileFonts || global[0] !== fileGlobal) {
    throw new CompileError(
      `${screen}: helmet styles in template.html differ from helmet.fonts.css / helmet.global.css`,
    )
  }
  return { fonts: fonts[0]!, global: global[0]! }
}

/** fonts.css: the @font-face blocks with every url("<uuid>") rewritten to /fonts/<file>.woff2. Family names unchanged. */
export function rewriteFontCss(root: string, screen: string, css: string): string {
  const manifest = JSON.parse(read(root, 'design/extracted/fonts/manifest.json')) as {
    uuidToFilePerScreen: Record<string, Record<string, string>>
  }
  const map = manifest.uuidToFilePerScreen[screen]
  if (!map) throw new CompileError(`fonts manifest has no entry for ${screen}`)
  let n = 0
  const out = css.replace(/url\("([0-9a-f-]{36})"\)/g, (_, uuid: string) => {
    const file = map[uuid]
    if (!file) throw new CompileError(`${screen}: font url ${uuid} is not in the fonts manifest`)
    n++
    return `url("/fonts/${file}")`
  })
  if (n === 0 || /url\("[0-9a-f-]{36}"\)/.test(out))
    throw new CompileError(`${screen}: font url rewrite incomplete`)
  return out
}

export interface ScreenResult {
  outputs: Outputs
  fontsCss: string
  tplCount: number
}

export function compileScreen(screen: ScreenId, opts: CompileOptions): ScreenResult {
  const { root } = opts
  const templatePath = path.join('design/extracted', screen, 'template.html')
  const template = read(root, templatePath)
  const metaJson = JSON.parse(read(root, 'design/extracted', screen, 'meta.json')) as {
    name: string
    dataProps: { $preview?: unknown } | null
  }
  const cfg = loadPatchConfig(root, screen)

  const { nodes, tplCount } = parseTemplate(template)
  const css = helmetCss(root, screen, nodes)
  applyPatches(nodes, cfg, screen)
  applyCopyToTree(nodes, cfg.copyEntries)

  const meta = { screen, name: metaJson.name, variant: opts.variant, tplCount }
  const header = [
    '// AUTO-GENERATED by tools/dc-compile. DO NOT EDIT.',
    `// source: ${templatePath} sha256:${sha(template).slice(0, 16)} patches sha256:${cfg.sha.slice(0, 16)} compiler:${COMPILER_VERSION} variant:${opts.variant}${opts.tplIds ? ' tpl-ids' : ''}`,
  ]
  const emitter = new Emitter({
    screen,
    tplIds: opts.tplIds || opts.variant === 'parity',
    allowComplexExpr: opts.allowComplexExpr,
  })
  const { tsx, bindings } = emitter.emit(nodes, header, meta)

  // Original runtime appends FULL_PAGE_CSS to <head> at boot unless the design declares $preview (only Operations does).
  const hasPreview = !!(metaJson.dataProps && '$preview' in metaJson.dataProps)
  const screenCss = hasPreview ? css.global : fullPageCss(root) + '\n' + css.global

  const logicSrc = applyCopy(
    read(root, 'design/extracted', screen, 'logic.original.js'),
    cfg.copyEntries,
    'logic',
  )

  const generatedHeader = '// AUTO-GENERATED by tools/dc-compile. DO NOT EDIT.\n'
  const outputs: Outputs = {
    [`${screen}.tsx`]: tsx,
    [`${screen}.bindings.json`]: JSON.stringify(bindings, null, 2) + '\n',
    [`${screen}.screen.css`]: screenCss,
    [`${screen}.styles.ts`]:
      `${generatedHeader}// The screen's global CSS, injected into <head> by ScreenStyle (same text as ${screen}.screen.css).\n` +
      `export const screenCss: string = ${JSON.stringify(screenCss)}\n`,
    [`${screen}.logic.ts`]:
      `${generatedHeader}// source: design/extracted/${screen}/logic.original.js sha256:${sha(logicSrc).slice(0, 16)} (the original DCLogic script, evaluated by loadLogic)\n` +
      `export const logicSource: string = ${JSON.stringify(logicSrc)}\n`,
  }
  return { outputs, fontsCss: rewriteFontCss(root, screen, css.fonts), tplCount }
}

export interface CompileAll {
  perScreen: Partial<Record<ScreenId, Outputs>>
  shared: Outputs
  tplCounts: Partial<Record<ScreenId, number>>
}

export function compileScreens(screens: readonly ScreenId[], opts: CompileOptions): CompileAll {
  const perScreen: CompileAll['perScreen'] = {}
  const tplCounts: CompileAll['tplCounts'] = {}
  const fonts = new Map<string, ScreenId>()
  for (const s of screens) {
    const r = compileScreen(s, opts)
    perScreen[s] = r.outputs
    tplCounts[s] = r.tplCount
    fonts.set(r.fontsCss, s)
  }
  const shared: Outputs = {}
  if (fonts.size > 1) {
    throw new CompileError(
      `font-face blocks differ between screens after url rewrite (${[...fonts.values()].join(', ')})`,
    )
  }
  if (fonts.size === 1) {
    const [css] = [...fonts.keys()]
    // No header comment: two adjacent comments crash Next's CSS minimizer (cssnano-simple) on this file.
    shared['src/styles/fonts.css'] = css
    const manifest = JSON.parse(read(opts.root, 'design/extracted/fonts/manifest.json')) as {
      files: Record<string, unknown>
    }
    for (const f of Object.keys(manifest.files).sort()) {
      shared[`public/fonts/${f}`] = fs.readFileSync(path.join(opts.root, 'design/extracted/fonts', f))
    }
  }
  return { perScreen, shared, tplCounts }
}
