// Generates src/data/ports/settings-schema.d.ts: the types of the endpoints the Settings screen uses, from the
// backend's OpenAPI document (the same source as `pnpm gen:api`, restricted to the Settings paths so the file stays
// small and does not collide with the other screens' generated types).
//   pnpm tsx scripts/gen-settings-schema.ts           write the file
//   pnpm tsx scripts/gen-settings-schema.ts --check   exit 1 when the committed file differs from a fresh generation
import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'
import { resolveSpecPath } from '../src/data/gen-api'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUT = path.join(root, 'src/data/ports/settings-schema.d.ts')

export const SETTINGS_PATHS = [
  '/api/v1/settings/bundle',
  '/api/v1/settings/hours',
  '/api/v1/settings/rules',
  '/api/v1/settings/auto-federal-holidays',
  '/api/v1/closures',
  '/api/v1/closures/{id}',
  '/api/v1/closures/preview',
  '/api/v1/emergency',
  '/api/v1/emergency/close',
  '/api/v1/emergency/reopen',
  '/api/v1/emergency/preview',
  '/api/v1/emergency/history',
  '/api/v1/employees',
  '/api/v1/employees/{id}',
  '/api/v1/employees/{id}/deactivate',
  '/api/v1/employees/{id}/reactivate',
  '/api/v1/roles',
  '/api/v1/roles/{id}',
  '/api/v1/roles/{id}/limits/{kind}',
  '/api/v1/roles/{id}/permissions/{key}',
  '/api/v1/services',
  '/api/v1/services/{id}/checklist',
  '/api/v1/vip',
  '/api/v1/vip/clients',
  '/api/v1/vip/clients/{customerId}',
  '/api/v1/vip/holds',
  '/api/v1/vip/holds/{id}',
  '/api/v1/arrival-settings',
] as const

export async function generate(specText: string): Promise<string> {
  const spec = JSON.parse(specText) as { paths: Record<string, unknown> }
  const keep = new Set<string>(SETTINGS_PATHS)
  const subset = {
    ...spec,
    paths: Object.fromEntries(Object.entries(spec.paths).filter(([p]) => keep.has(p))),
  }
  const missing = SETTINGS_PATHS.filter((p) => !(p in subset.paths))
  if (missing.length) throw new Error(`not in the OpenAPI document: ${missing.join(', ')}`)
  const ast = await openapiTS(subset as never, { alphabetize: true, exportType: true })
  const sha = crypto.createHash('sha256').update(JSON.stringify(subset)).digest('hex').slice(0, 16)
  return (
    `// AUTO-GENERATED by scripts/gen-settings-schema.ts from the backend docs/openapi.json, Settings paths only (sha256:${sha}). DO NOT EDIT.\n` +
    '// Regenerate with `pnpm tsx scripts/gen-settings-schema.ts`; add --check to fail on drift.\n' +
    '/* eslint-disable */\n' +
    astToString(ast)
  )
}

async function main(argv: string[]): Promise<number> {
  const specPath = resolveSpecPath()
  if (!fs.existsSync(specPath)) {
    console.error(`gen-settings-schema: ${specPath} not found. Set OASIS_OPENAPI or OASIS_BACKEND_PATH.`)
    return 2
  }
  const out = await generate(fs.readFileSync(specPath, 'utf8'))
  if (argv.includes('--check')) {
    const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : ''
    if (have !== out) {
      console.error('gen-settings-schema --check: settings-schema.d.ts is out of date')
      return 1
    }
    console.log('gen-settings-schema --check: up to date')
    return 0
  }
  fs.writeFileSync(OUT, out)
  console.log(`gen-settings-schema: wrote ${path.relative(root, OUT)} (${out.length} bytes)`)
  return 0
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).then((c) => (process.exitCode = c))
}
