// Generates src/data/ports/operations-schema.d.ts: the types of the endpoints the live Operations screen uses, from the
// backend's OpenAPI document (the same source as `pnpm gen:api`, restricted to the Operations paths so the file stays
// small and does not collide with the other screens' generated types).
//   OASIS_BACKEND_PATH=~/oasis/wt/d9-be pnpm tsx scripts/gen-operations-schema.ts          write the file
//   pnpm tsx scripts/gen-operations-schema.ts --check   exit 1 when the committed file differs from a fresh generation
import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'
import { resolveSpecPath } from '../src/data/gen-api'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUT = path.join(root, 'src/data/ports/operations-schema.d.ts')

export const OPERATIONS_PATHS = [
  '/api/v1/ops/snapshot',
  '/api/v1/ops/alerts',
  '/api/v1/ops/kpis',
  '/api/v1/calendar/summary',
  '/api/v1/calendar/day',
  '/api/v1/availability',
  '/api/v1/bays',
  '/api/v1/staff',
  '/api/v1/appointments',
  '/api/v1/appointments/{id}',
  '/api/v1/appointments/{id}/addons/{serviceId}',
  '/api/v1/appointments/{id}/advance',
  '/api/v1/appointments/{id}/arrive',
  '/api/v1/appointments/{id}/assign-bay',
  '/api/v1/appointments/{id}/cancel',
  '/api/v1/appointments/{id}/checklist/bulk',
  '/api/v1/appointments/{id}/checklist/items/{itemId}',
  '/api/v1/appointments/{id}/complete',
  '/api/v1/appointments/{id}/confirm',
  '/api/v1/appointments/{id}/membership-perks/apply',
  '/api/v1/appointments/{id}/messages',
  '/api/v1/appointments/{id}/no-show',
  '/api/v1/appointments/{id}/notify-ready',
  '/api/v1/appointments/{id}/photos/note',
  '/api/v1/appointments/{id}/photos/presign',
  '/api/v1/appointments/{id}/photos/{photoId}',
  '/api/v1/appointments/{id}/photos/{photoId}/complete',
  '/api/v1/appointments/{id}/pickup',
  '/api/v1/appointments/{id}/prep-bay',
  '/api/v1/appointments/{id}/reopen',
  '/api/v1/appointments/{id}/reschedule',
  '/api/v1/appointments/{id}/start',
  '/api/v1/customers',
  '/api/v1/customers/{id}/membership',
  '/api/v1/customers/{id}/messages',
  '/api/v1/customers/{id}/messages/read',
  '/api/v1/messages/templates',
  '/api/v1/services',
] as const

export async function generate(specText: string): Promise<string> {
  const spec = JSON.parse(specText) as { paths: Record<string, unknown> }
  const keep = new Set<string>(OPERATIONS_PATHS)
  const subset = {
    ...spec,
    paths: Object.fromEntries(Object.entries(spec.paths).filter(([p]) => keep.has(p))),
  }
  const missing = OPERATIONS_PATHS.filter((p) => !(p in subset.paths))
  if (missing.length) throw new Error(`not in the OpenAPI document: ${missing.join(', ')}`)
  const ast = await openapiTS(subset as never, { alphabetize: true, exportType: true })
  const sha = crypto.createHash('sha256').update(JSON.stringify(subset)).digest('hex').slice(0, 16)
  return (
    `// AUTO-GENERATED by scripts/gen-operations-schema.ts from the backend docs/openapi.json, Operations paths only (sha256:${sha}). DO NOT EDIT.\n` +
    '// Regenerate with `pnpm tsx scripts/gen-operations-schema.ts`; add --check to fail on drift.\n' +
    '/* eslint-disable */\n' +
    astToString(ast)
  )
}

async function main(argv: string[]): Promise<number> {
  const specPath = resolveSpecPath()
  if (!fs.existsSync(specPath)) {
    console.error(`gen-operations-schema: ${specPath} not found. Set OASIS_OPENAPI or OASIS_BACKEND_PATH.`)
    return 2
  }
  const out = await generate(fs.readFileSync(specPath, 'utf8'))
  if (argv.includes('--check')) {
    const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : ''
    if (have !== out) {
      console.error('gen-operations-schema --check: operations-schema.d.ts is out of date')
      return 1
    }
    console.log('gen-operations-schema --check: up to date')
    return 0
  }
  fs.writeFileSync(OUT, out)
  console.log(`gen-operations-schema: wrote ${path.relative(root, OUT)} (${out.length} bytes)`)
  return 0
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).then((c) => (process.exitCode = c))
}
