// Generates src/data/http/schema.d.ts from the backend's OpenAPI document with openapi-typescript.
//   pnpm gen:api           write the file (reads $OASIS_OPENAPI, else $OASIS_BACKEND_PATH/docs/openapi.json, else ../backend)
//   pnpm gen:api --check   exit 1 when the committed file differs from a fresh generation (CI drift guard)
import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const OUT = path.join(root, 'src/data/http/schema.d.ts')

export function resolveSpecPath(env: NodeJS.ProcessEnv = process.env): string {
  if (env.OASIS_OPENAPI) return path.resolve(env.OASIS_OPENAPI)
  return path.resolve(root, env.OASIS_BACKEND_PATH || '../backend', 'docs/openapi.json')
}

export async function generate(specText: string): Promise<string> {
  const spec = JSON.parse(specText) as Record<string, unknown>
  const ast = await openapiTS(spec as never, { alphabetize: true, exportType: true })
  const sha = crypto.createHash('sha256').update(specText).digest('hex').slice(0, 16)
  return (
    `// AUTO-GENERATED by src/data/gen-api.ts from the backend docs/openapi.json (sha256:${sha}). DO NOT EDIT.\n` +
    '// Regenerate with `pnpm gen:api`; `pnpm gen:api --check` fails on drift.\n' +
    '/* eslint-disable */\n' +
    astToString(ast)
  )
}

async function main(argv: string[]): Promise<number> {
  const specPath = resolveSpecPath()
  if (!fs.existsSync(specPath)) {
    console.error(`gen:api: ${specPath} not found. Set OASIS_OPENAPI or OASIS_BACKEND_PATH.`)
    return 2
  }
  const out = await generate(fs.readFileSync(specPath, 'utf8'))
  if (argv.includes('--check')) {
    const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : ''
    if (have !== out) {
      console.error(
        'gen:api --check: src/data/http/schema.d.ts is out of date; run `pnpm gen:api` and commit it.',
      )
      return 1
    }
    console.log('gen:api --check: up to date')
    return 0
  }
  fs.mkdirSync(path.dirname(OUT), { recursive: true })
  fs.writeFileSync(OUT, out)
  console.log(`gen:api: wrote ${path.relative(root, OUT)} from ${specPath}`)
  return 0
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).then((c) => (process.exitCode = c))
}
